name: container-build
on:
  push:
    paths:
      - 'data/Dockerfiles/parsedmarc/**'
  schedule:
    - cron: '0 0 14 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          dockerfile: data/Dockerfiles/parsedmarc/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: patschi/parsedmarc
          tags: latest
          add_git_labels: true
